[package]
name = "futures-preview"
edition = "2018"
version = "0.3.0-alpha.10"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
keywords = ["futures", "async", "future"]
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://rust-lang-nursery.github.io/futures-rs"
documentation = "https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.10/futures"
description = """
An implementation of futures and streams featuring zero allocations,
composability, and iterator-like interfaces.
"""
categories = ["asynchronous"]

[lib]
name = "futures"

[badges]
travis-ci = { repository = "rust-lang-nursery/futures-rs" }
appveyor = { repository = "rust-lang-nursery/futures-rs" }

[dependencies]
futures-core-preview = { path = "../futures-core", version = "0.3.0-alpha.10", default-features = false }
futures-channel-preview = { path = "../futures-channel", version = "0.3.0-alpha.10", default-features = false }
futures-executor-preview = { path = "../futures-executor", version = "0.3.0-alpha.10", default-features = false }
futures-io-preview = { path = "../futures-io", version = "0.3.0-alpha.10", default-features = false }
futures-sink-preview = { path = "../futures-sink", version = "0.3.0-alpha.10", default-features = false }
futures-util-preview = { path = "../futures-util", version = "0.3.0-alpha.10", default-features = false }

[dev-dependencies]
pin-utils = "0.1.0-alpha.4"
futures-test-preview = { path = "../futures-test", version = "0.3.0-alpha.10", default-features = false }
tokio = "0.1.11"

[features]
nightly = ["futures-util-preview/nightly", "futures-core-preview/nightly"]
std = ["futures-core-preview/std", "futures-executor-preview/std", "futures-io-preview/std", "futures-sink-preview/std", "futures-util-preview/std"]
default = ["std"]
compat = ["std", "futures-util-preview/compat"]
io-compat = ["compat", "futures-util-preview/io-compat"]
tokio-compat = ["compat", "futures-util-preview/tokio-compat"]
